services:
  asciinema:
    #image: ghcr.io/asciinema/asciinema-server:custom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:4000'
    environment:
      - SECRET_KEY_BASE=gtWf2hnMRJoqZZmHSvyX2W4tMfRNCVUo15aHopHghJiIU0w6rcdZkt5JQiSatLjh
      - URL_HOST=localhost
      - URL_PORT=80
      - SIGN_UP_DISABLED=false
    volumes:
      - asciinema_data:/var/opt/asciinema
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: docker.io/library/postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  asciinema_data:
  postgres_data:
